In [1]:
#1. Import the Numpy package under the name np
import numpy as np

In [2]:
#2.Create a null vector of size 10
null_vector= np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# 3.Create a null vector of size 10 but the fifth value which is 1
null_vector= np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#4. Create a vector with values ranging from 10 to 49
vector= np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#5. Reverse a vector (the first element becomes last)
reverse_vector = [1, 2, 3, 4, 5]
reverse_vector.reverse()
print(reverse_vector)

[5, 4, 3, 2, 1]


In [6]:
# 6.Create a 3x3 matrix with values ranging from 0 to 8
mat= np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# 7.Find indices of non­zero elements from [1,2,0,0,4,0]
arr=np.array([1,2,0,0,4,0])
nonZero=list(np.nonzero(arr)[0])
print(nonZero)
# OR
# arr=[1,2,0,0,4,0]
# nonZero=np.nonzero(arr)
# print(nonZero
# OR
# li = [2, 0, 5, 7, 0, 9]
# li_new = []
# for i in range(len(li)):
#     if li[i]!=0:
#         li_new.append(i)
# print(li_new)

[0, 1, 4]


In [8]:
# 8.Create a 3x3x3 array with random values
ranVal = np.random.random((3,3,3))
print(ranVal)

[[[0.83560033 0.63055936 0.45410583]
  [0.47765784 0.69370184 0.41287714]
  [0.58038431 0.27645602 0.73797578]]

 [[0.25620253 0.43272589 0.96935849]
  [0.91533674 0.87711566 0.78312137]
  [0.4890782  0.2507074  0.11195847]]

 [[0.74785015 0.80320096 0.32788123]
  [0.62277596 0.0538529  0.17601937]
  [0.87541987 0.52659929 0.63020497]]]


In [9]:
# 9.Create a random vector of size 30 and find the mean value
ranVal = np.random.random((30))
ranVal.mean()
print(ranVal)

[0.91124051 0.06490877 0.07493889 0.88611161 0.99691019 0.75001634
 0.72030667 0.97083231 0.22559287 0.20086493 0.53163281 0.45023018
 0.59687158 0.51192306 0.21212083 0.43235005 0.53402957 0.8504788
 0.76778304 0.70111303 0.87144576 0.72859486 0.66292181 0.3199536
 0.96411143 0.22961571 0.68726859 0.36200105 0.5845483  0.95392312]


In [10]:
# 10.Create a 2d array with 1 on the border and 0 inside
arr= np.full((6,6),1)
arr[1:-1,1:-1]=0
print(arr)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [11]:
#11.Create an 8x8 matrix and fill it with a checkerboard pattern

arr= np.full((8,8),0)
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#12.What is the major difference between sets, lists, tuples and dictionaries?
Lists

    List is a collection which is ordered.
    Lists are mutable (changeable) .
    Allows duplicate members
    Brackets used to represent: []
    Lists are like arrays declared in other languages.

Tuples

    Collection of items which is ordered.
    Tuples are immutable (unchangeable) .
    Brackets used to represent: ()
    Only difference between tuples and lists are that lists can be changed.
    Tuples are faster than lists as they are immutable.

Sets

    Collection of Unordered and Unindexed items.
    Sets are mutable (changeable).
    Does not take duplicate Values.
    Sets are unordered, so you cannot be sure in which order the items will appear.
    Brackets used to represent: { }.
    Sets are not faster than lists however they have a upper hand when it comes to membership testing.

Dictionaries

    Key:Value Pair in Python
    A dictionary is a collection which is ordered, changeable and indexed.
    In Python dictionaries are written with curly brackets, and they have keys and values.
    Brackets used to represent: {}.

In [12]:
#13. Print first 10 natural numbers using while loop
i=1
while(i<=10):
    print(i)
    i+=1
    

1
2
3
4
5
6
7
8
9
10


In [13]:
#14. Print the numbers -10 to -1 using for loop.
for x in range(-10,0,1):
    print(x)


-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [14]:
# 15. Print the message “Done” after successful execution of any for a loop
for x in range(-10,0,1):
    print(x)
print("Done")

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
Done


In [15]:
# 16.Create a random vector of size 10 and sort it
rand= np.random.random(10)
rand.sort()
print(rand)

[0.00751236 0.03270424 0.06908654 0.07643772 0.16407246 0.16773663
 0.3283402  0.55786405 0.6001629  0.62823783]


In [16]:
# 17.Execute any three math functions using NumPy.
#Sum
x,y=10,2
a=[1,2,4]
val= np.sum([x,y])
print('Sum: ',val)
#Sine
print("sine :", np.sin(a))
#Log
valL= np.log([x,y])
print('log: ',valL)

Sum:  12
sine : [ 0.84147098  0.90929743 -0.7568025 ]
log:  [2.30258509 0.69314718]
