# Data Structures

<img src = https://res.cloudinary.com/practicaldev/image/fetch/s--oTgfo1EL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png width = 800>

In [8]:
# !conda list

In [13]:
import numpy as np
# help(numpy)

In [14]:
np.array([1,2,3])

array([1, 2, 3])

In [15]:
# Scalar
np.array(1)

array(1)

# Vector

In [18]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [19]:
a.ndim

1

In [21]:
b = np.array([[1,2,3]])
print(b.T)

[[1]
 [2]
 [3]]


In [22]:
type(b)

numpy.ndarray

# Matrix

In [23]:
m = np.matrix([[1,2,3], [4,5,6]])
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [24]:
type(m)

numpy.matrix

In [25]:
m.shape

(2, 3)

# Arrays

In [28]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [29]:
type(a)

numpy.ndarray

In [30]:
a.ndim

1

In [31]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
type(b)

numpy.ndarray

In [33]:
b.ndim

2

In [34]:
c = np.array([[[1,2,3], [4,5,6], [8,9,10]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 8,  9, 10]]])

In [35]:
c.ndim

3

In [36]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
b.shape

(2, 3)

In [38]:
b.size

6

In [39]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
a.ndim

2

In [43]:
v = np.ones((3,3))
v

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
v.ndim

2

In [45]:
v = np.full((3,3), 10)
v

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [48]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [49]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [52]:
d = np.array([np.arange(1,6,2),
             np.linspace(10,20,3)])
d

array([[ 1.,  3.,  5.],
       [10., 15., 20.]])

# Accessing Values from Arrays

In [53]:
a = np.array([np.linspace(1,10,3),
             np.linspace(10,20,3),
             np.linspace(20,30,3)])

a

array([[ 1. ,  5.5, 10. ],
       [10. , 15. , 20. ],
       [20. , 25. , 30. ]])

In [54]:
a.ndim

2

In [55]:
a.shape

(3, 3)

In [56]:
a[0]

array([ 1. ,  5.5, 10. ])

In [57]:
a[0,0]

1.0

In [58]:
a

array([[ 1. ,  5.5, 10. ],
       [10. , 15. , 20. ],
       [20. , 25. , 30. ]])

In [59]:
a[2,1]

25.0

In [60]:
a[:2,:2]

array([[ 1. ,  5.5],
       [10. , 15. ]])

In [61]:
a[1:,1:]

array([[15., 20.],
       [25., 30.]])

# Boolean Indexing

In [62]:
a

array([[ 1. ,  5.5, 10. ],
       [10. , 15. , 20. ],
       [20. , 25. , 30. ]])

In [63]:
a > 10

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [64]:
b = [1,2,3,4,5,6,7,8]
b

[1, 2, 3, 4, 5, 6, 7, 8]

In [65]:
b > 2

TypeError: '>' not supported between instances of 'list' and 'int'

In [66]:
for i in b:
    if i > 2:
        print(i)

3
4
5
6
7
8


In [67]:
a

array([[ 1. ,  5.5, 10. ],
       [10. , 15. , 20. ],
       [20. , 25. , 30. ]])

In [68]:
a[a > 10]

array([15., 20., 20., 25., 30.])

In [69]:
expr = a > 10

In [70]:
print('Values Greater than 10 in the Array A is', a[expr])

Values Greater than 10 in the Array A is [15. 20. 20. 25. 30.]


# Elementwise Operations

In [71]:
scalar = np.array(10)
scalar

array(10)

In [72]:
scalar + 10

20

In [73]:
scalar - 10

0

In [74]:
scalar * 10

100

In [75]:
scalar / 10

1.0

In [76]:
scalar // 10

1

In [77]:
scalar ** 10

1410065408

# Vector 

In [79]:
vector = np.array([1,2,3,4,5])
vector

array([1, 2, 3, 4, 5])

In [81]:
a = [1, 2, 3, 4, 5]
a + 10

TypeError: can only concatenate list (not "int") to list

In [82]:
vector + 10

array([11, 12, 13, 14, 15])

In [83]:
vector - 10

array([-9, -8, -7, -6, -5])

In [84]:
vector * 10

array([10, 20, 30, 40, 50])

In [85]:
vector / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [86]:
vector // 10

array([0, 0, 0, 0, 0], dtype=int32)

In [87]:
vector ** 10

array([      1,    1024,   59049, 1048576, 9765625], dtype=int32)

# Matrix

In [88]:
matrix = np.array([[1,2,3,4],[4,5,6,7]])
matrix

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [89]:
matrix + 10

array([[11, 12, 13, 14],
       [14, 15, 16, 17]])

In [90]:
matrix - 10

array([[-9, -8, -7, -6],
       [-6, -5, -4, -3]])

In [91]:
matrix * 10

array([[10, 20, 30, 40],
       [40, 50, 60, 70]])

In [92]:
matrix / 10

array([[0.1, 0.2, 0.3, 0.4],
       [0.4, 0.5, 0.6, 0.7]])

In [93]:
matrix ** 10

array([[        1,      1024,     59049,   1048576],
       [  1048576,   9765625,  60466176, 282475249]], dtype=int32)

In [94]:
matrix // 10

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

# Array

In [96]:
ndarray = np.array([[[1,2,3], [3,4,5], [6,7,8]]])
ndarray

array([[[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]]])

In [97]:
ndarray.ndim

3

In [98]:
ndarray + 10

array([[[11, 12, 13],
        [13, 14, 15],
        [16, 17, 18]]])

# Broadcasting & Stacking

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [4]:
a.shape

(2, 2)

In [5]:
b.shape

(1, 2)

In [10]:
b.T.shape

(2, 1)

In [7]:
c = np.concatenate((a,b))
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
c.shape

(3, 2)

In [9]:
d = np.concatenate((a,b), axis = 1)
d

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [11]:
d = np.concatenate((a,b.T), axis = 1)
d

array([[1, 2, 5],
       [3, 4, 6]])

In [13]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

# Broadcasting

In [15]:
a

array([[1, 2],
       [3, 4]])

In [16]:
b

array([[5, 6]])

In [17]:
a.shape

(2, 2)

In [18]:
b.shape

(1, 2)

In [19]:
a + b

array([[ 6,  8],
       [ 8, 10]])

In [20]:
a - b

array([[-4, -4],
       [-2, -2]])

In [21]:
a * b

array([[ 5, 12],
       [15, 24]])

In [22]:
c = np.random.randint(1,100,(3,3))
c

array([[60,  5, 42],
       [29, 46, 59],
       [42, 76, 15]])

In [23]:
c.shape

(3, 3)

In [24]:
a.shape

(2, 2)

In [25]:
b.shape

(1, 2)

In [26]:
a + c

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

# Axis-wise Operations

In [32]:
c

array([[60,  5, 42],
       [29, 46, 59],
       [42, 76, 15]])

In [33]:
c.sum()

374

In [35]:
print('Column wise Addition', c.sum(axis = 0))
print('Row wise Addition', c.sum(axis = 1))

Column wise Addition [131 127 116]
Row wise Addition [107 134 133]


In [36]:
c.mean()

41.55555555555556

In [37]:
print('Column wise Average', c.mean(axis = 0))
print('Row wise Average', c.mean(axis = 1))

Column wise Average [43.66666667 42.33333333 38.66666667]
Row wise Average [35.66666667 44.66666667 44.33333333]


In [38]:
c.std()

21.213785408503234

In [39]:
print('Column wise SD', c.std(axis = 0))
print('Row wise SD', c.std(axis = 1))

Column wise SD [12.71045064 29.10135545 18.11690432]
Row wise SD [22.89589968 12.28368385 24.95774206]


In [40]:
c.var()

450.0246913580247

In [41]:
print('Column wise Var', c.var(axis = 0))
print('Row wise Var', c.var(axis = 1))

Column wise Var [161.55555556 846.88888889 328.22222222]
Row wise Var [524.22222222 150.88888889 622.88888889]


In [42]:
c.min()

5

In [43]:
c.max()

76

# Reshape, Ravel, Split and Random

In [56]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
b = np.arange(9)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Reshape

In [59]:
b.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
a.reshape(-1)

array([1, 2, 3, 4, 5, 6])

# Ravel

In [61]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [63]:
c = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [64]:
c.ndim

3

In [65]:
c.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split

In [67]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
np.split(b, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [70]:
np.split(b, (3,6,8))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8])]

# Random

In [72]:
np.random.randn(3,3)

array([[-0.39275224,  1.78933755,  0.51922872],
       [-0.07836133, -1.53855199,  0.92565253],
       [-1.14371462, -0.72520034, -1.74189384]])

In [73]:
np.random.sample((3,3))

array([[0.26361369, 0.93562327, 0.33925962],
       [0.96216845, 0.29509637, 0.04906482],
       [0.66079045, 0.68931381, 0.45288179]])

In [79]:
np.random.randint(1,10, (3,3))

array([[6, 7, 8],
       [8, 2, 6],
       [2, 3, 8]])

In [90]:
np.random.seed(1)
np.random.randint(1,10, (3,3))

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]])